#!/usr/bin/env node
// Reads lib/funnel/canon-volynsky.md and emits lib/funnel/canon.generated.ts
// with the file content as an exported string constant.
// Run before build: `npm run build` includes this via prebuild hook.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");
const sourcePath = resolve(repoRoot, "lib/funnel/canon-volynsky.md");
const targetPath = resolve(repoRoot, "lib/funnel/canon.generated.ts");

const md = readFileSync(sourcePath, "utf-8");

const escaped = md
  .replace(/\\/g, "\\\\")
  .replace(/`/g, "\\`")
  .replace(/\$\{/g, "\\${");

const ts = `// AUTO-GENERATED from canon-volynsky.md by scripts/build-canon.mjs
// Do not edit this file directly — edit the .md and run \`node scripts/build-canon.mjs\`.

export const CANON_VOLYNSKY = \`${escaped}\`;
`;

writeFileSync(targetPath, ts, "utf-8");
const kb = (Buffer.byteLength(ts, "utf-8") / 1024).toFixed(1);
console.log(`canon.generated.ts written (${kb} KB, ${md.split(/\s+/).length} words from source)`);
